server:
  port: 8080

spring:
  # 主数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/study?useSSL=false&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    # 多数据源配置
    multi:
      auto-init: true
      enable: true



dataSource:
  # 要启用PSCache
  maxPoolPreparedStatementPerConnectionSize: 20
  # 初始化时建立物理连接的个数
  initialSize: 10
  # 最小连接池数量
  minIdle: 5
  # 最大连接池数量
  maxActive: 100
  # 获取连接时最大等待时间，单位毫秒
  maxWait: 60000
  # 申请连接时执行validationQuery检测连接是否有效
  testOnBorrow: true
  # 归还连接时执行validationQuery检测连接是否有效归还连接时执行validationQuery检测连接是否有效
  testOnReturn: false
  # 建议配置为true，不影响性能，并且保证安全性
  testWhileIdle: false
  # Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接
  timeBetweenEvictionRunsMillis: 1800000
  # 连接保持空闲而不被驱逐的最小时间
  minEvictableIdleTimeMillis: 1800000
  # 是否缓存preparedStatement，也就是PSCache
  poolPreparedStatements: true
  # 插件配置监控统计用的stat、log4j、wall
  filters: stat,wall

db:
  dynamic:
    datasource:
      path: jdbc:mysql://%s:3306/%s?useSSL=false&useUnicode=true
      # username: root
      # password: root

mybatis:
  configuration:
    # 自动转驼峰，在多数据源下会失效
    # 1.手动配置xml映射关系 2. MyBatis 配置 SqlSessionFactoryBean ，注入 org.apache.ibatis.session.Configuration
    map-underscore-to-camel-case: true